name: Go

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

jobs:
  build:
    name: Build and test ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Vet
        run: go vet -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Build
        run: go build -v ./...

      - name: Install Spice (https://install.spiceai.org) (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl https://install.spiceai.org | /bin/bash
          echo "$HOME/.spice/bin" >> $GITHUB_PATH
          $HOME/.spice/bin/spice install
      
      - name: Install Spice (https://install.spiceai.org) (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install spiceai/spiceai/spice
          brew install spiceai/spiceai/spiced

      - name: install Spice (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          curl -L "https://install.spiceai.org/Install.ps1" -o Install.ps1 && PowerShell -ExecutionPolicy Bypass -File ./Install.ps1

      - name: add Spice bin to PATH (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Add-Content $env:GITHUB_PATH (Join-Path $HOME ".spice\bin")
        shell: pwsh

      - name: Init and start spice app (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          spice init spice_qs
          cd spice_qs
          spice add spiceai/quickstart
          spiced &> spice.log &
          # time to initialize added dataset
          sleep 10

      - name: Init and start spice app (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          spice init spice_qs
          cd spice_qs
          spice add spiceai/quickstart
          Start-Process -FilePath spice run
          # time to initialize added dataset
          Start-Sleep -Seconds 10
        shell: pwsh

      - name: Test
        run: go test -v ./...
