name: Go

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

jobs:
  build_and_test:
    name: Build and test ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Vet
        run: go vet -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6

      - name: Build
        run: go build -v ./...

      - name: install Spice (https://install.spiceai.org)
        run: |
          curl https://install.spiceai.org | /bin/bash
          echo "$HOME/.spice/bin" >> $GITHUB_PATH

      - name: Init and start spice app
        run: |
          spice init spice_qs
          cd spice_qs
          spice add spiceai/quickstart
          spice run &> spice.log &
          # time to initialize added dataset
          sleep 10

      - name: Test
        run: go test -v ./...
