name: Manually Triggered Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag and release'
        required: true

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      tag-exists: ${{ steps.check-tag.outputs.tag-exists }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if tag exists
        id: check-tag
        run: |
          if git tag | grep -q "${{ github.event.inputs.version }}"; then
            echo "Tag exists"
            echo "tag-exists=1" >> "$GITHUB_OUTPUT"
          else
            echo "Tag does not exist"
            echo "tag-exists=0" >> "$GITHUB_OUTPUT"
          fi


  create-tag-and-release:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.tag-exists == '0'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create and push tag
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Draft a new release
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create ${{ github.event.inputs.version }} --title "Release ${{ github.event.inputs.version }}" --generate-notes --draft
