name: Manually Triggered Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag and release'
        required: true

jobs:
  check-and-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check if tag exists
        id: check-tag
        run: |
          if git tag | grep -q "${{ github.event.inputs.version }}"; then
            echo "Tag exists"
            echo "::set-output name=exists::1"
          else
            echo "Tag does not exist"
            echo "::set-output name=exists::0"
          fi

      - name: Create and push tag
        if: steps.check-tag.outputs.exists == '0'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Install GitHub CLI
        if: steps.check-tag.outputs.exists == '0'
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Draft a new release
        if: steps.check-tag.outputs.exists == '0'
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create ${{ github.event.inputs.version }} --title "Release ${{ github.event.inputs.version }}" --generate-notes --draft
